//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPHANMEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViPham
    {
        public string MSVIPHAM { get; set; }
        public string MSHS { get; set; }
        public string TENVIPHAM { get; set; }
        public decimal SLXEVIPHAM { get; set; }
        public Nullable<decimal> SOTIENPHAT { get; set; }
    
        public virtual HoSo HoSo { get; set; }
    }
}
