//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPHANMEM.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Xe
    {
        public string MSXE { get; set; }
        public string MSNV { get; set; }
        public string TENXE { get; set; }
        public string TENHANGXE { get; set; }
        public decimal SLXE { get; set; }
        public decimal SLĐCHUAN { get; set; }
        
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
